name: GitHub Actions Runner in Docker - Release
on:
  push:
    paths-ignore:
      - README.md
    tags:
      - "*"

jobs:
  debian_latest_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repo Files
        uses: actions/checkout@master
      - name: get version
        run: echo ::set-env name=TAG::${GITHUB_REF#refs/tags/}
      - name: Get GitHub organization or user
        run: echo ::set-env name=ORG::$(dirname ${GITHUB_REPOSITORY})
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }} docker.pkg.github.com
      - name: Build
        run: docker buildx build -f Dockerfile -t docker.pkg.github.com/${ORG}/github-runner:${TAG} --output "type=image,push=true" --platform linux/amd64,linux/arm/v7,linux/arm64 .
